;profile name=sample profile 0
usb report rate=1000
resolution 0=500
resolution 1=800
resolution 2=1100
resolution 3=1400
resolution 4=1700
default resolution profile=2
active resolution profile=2
button 0=button 1
button 1=button 2
button 2=button 3
button 3=resolution-down
button 4=resolution-alternate
button 5=resolution-up
button 6=wheel-left
button 7=wheel-right
button 8=KEY_HOME
button 9=profile-cycle-up
button 10=profile-cycle-down
