;profile name=sample profile 2
profile enable=enable
usb report rate=1000
default resolution profile=2
active resolution profile=2
resolution 0=1200
resolution 1=1400
resolution 2=1600
resolution 3=1800
resolution 4=2000
button 0=button 1
button 1=button 2
button 2=button 3
button 3=resolution-down
button 4=+KEY_LEFTCTRL KEY_W -KEY_LEFTCTRL
button 5=resolution-up
button 6=KEY_LEFT
button 7=KEY_RIGHT
button 8=KEY_HOME
button 9=profile-cycle-up
button 10=profile-cycle-down
