// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDeviceInfo(arg1:string):Promise<string>;

export function ListDevices():Promise<Array<main.Device>>;

export function RatbagctlAvailable():Promise<boolean>;

export function SetActiveProfile(arg1:string,arg2:number):Promise<string>;

export function SetDPI(arg1:string,arg2:number,arg3:number,arg4:number):Promise<string>;

export function SetReportRate(arg1:string,arg2:number,arg3:number):Promise<string>;
