// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableButton(arg1, arg2) {
  return window['go']['main']['App']['DisableButton'](arg1, arg2);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function SetButtonAction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetButtonAction'](arg1, arg2, arg3, arg4);
}

export function SetButtonMacro(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetButtonMacro'](arg1, arg2, arg3);
}

export function SetProfileActive(arg1, arg2) {
  return window['go']['main']['App']['SetProfileActive'](arg1, arg2);
}

export function SetProfileEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProfileEnabled'](arg1, arg2, arg3);
}

export function SetProfileName(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProfileName'](arg1, arg2, arg3);
}

export function SetReportRate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetReportRate'](arg1, arg2, arg3);
}

export function SetResolution(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetResolution'](arg1, arg2, arg3);
}

export function SetResolutionActive(arg1, arg2) {
  return window['go']['main']['App']['SetResolutionActive'](arg1, arg2);
}

export function SetResolutionDefault(arg1, arg2) {
  return window['go']['main']['App']['SetResolutionDefault'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
