// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisableButton(arg1:string,arg2:string):Promise<void>;

export function ListDevices():Promise<Array<main.Device>>;

export function SetButtonAction(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SetButtonMacro(arg1:string,arg2:string,arg3:Array<main.MacroEvent>):Promise<void>;

export function SetProfileActive(arg1:string,arg2:string):Promise<void>;

export function SetProfileEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetProfileName(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetReportRate(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetResolution(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetResolutionActive(arg1:string,arg2:string):Promise<void>;

export function SetResolutionDefault(arg1:string,arg2:string):Promise<void>;

export function Status():Promise<main.Status>;
