// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function RatbagctlAvailable() {
  return window['go']['main']['App']['RatbagctlAvailable']();
}

export function SetActiveProfile(arg1, arg2) {
  return window['go']['main']['App']['SetActiveProfile'](arg1, arg2);
}

export function SetDPI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetDPI'](arg1, arg2, arg3, arg4);
}

export function SetReportRate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetReportRate'](arg1, arg2, arg3);
}
